# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=25)),
                ('usex', models.CharField(max_length=13)),
                ('uemail', models.CharField(max_length=20)),
                ('uage', models.IntegerField()),
            ],
        ),
    ]
