# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=35)),
                ('u_sex', models.CharField(max_length=5)),
                ('u_addr', models.CharField(max_length=56)),
                ('u_age', models.IntegerField()),
            ],
        ),
    ]
