# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucmp', models.CharField(max_length=30)),
                ('uaddr', models.CharField(max_length=30)),
            ],
        ),
    ]
