# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='uinfo',
            name='u_info',
            field=models.CharField(default='', editable=False, max_length=25),
        ),
    ]
